#! /bin/bash

docker build -t compile-proto .
docker create --name compile-proto-binaries compile-proto
rm -rf ./clients/
docker cp compile-proto-binaries:/home/protos/clients ./clients/
docker rm compile-proto-binaries