# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: StrapiEvents.proto for package 'VocaSystem'

require 'grpc'
require 'StrapiEvents_pb'

module VocaSystem
  module StrapiEvents
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'VocaSystem.StrapiEvents'

      rpc :DispatchEvent, ::VocaSystem::StrapiEventReq, ::VocaSystem::StrapiEventResp
    end

    Stub = Service.rpc_stub_class
  end
end
