# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StrapiEvents.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("StrapiEvents.proto", :syntax => :proto3) do
    add_message "VocaSystem.StrapiEventReq" do
      optional :instanceUUID, :string, 1
      optional :level, :enum, 2, "VocaSystem.INFO_LEVEL"
      optional :saga, :enum, 3, "VocaSystem.SAGA"
      optional :message, :string, 4
      optional :payload, :string, 5
    end
    add_message "VocaSystem.StrapiEventResp" do
      optional :ok, :bool, 1
    end
    add_enum "VocaSystem.INFO_LEVEL" do
      value :DEBUG, 0
      value :INFO, 1
      value :WARN, 2
      value :ERROR, 3
    end
    add_enum "VocaSystem.SAGA" do
      value :DECIDIM_ASSETS, 0
      value :DECIDIM_SEED, 1
      value :DECIDIM_ADMIN_CREATED, 2
      value :DECIDIM_READY, 3
    end
  end
end

module VocaSystem
  StrapiEventReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaSystem.StrapiEventReq").msgclass
  StrapiEventResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaSystem.StrapiEventResp").msgclass
  INFO_LEVEL = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaSystem.INFO_LEVEL").enummodule
  SAGA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaSystem.SAGA").enummodule
end
