# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: strapi_events.proto for package 'voca_system'

require 'grpc'
require 'strapi_events_pb'

module VocaSystem
  module StrapiEvents
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'voca_system.StrapiEvents'

      rpc :DispatchEvent, ::VocaSystem::StrapiEventRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
