# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strapi_events.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("strapi_events.proto", :syntax => :proto3) do
    add_message "voca_system.StrapiEventRequest" do
      optional :instanceUUID, :string, 1
      optional :level, :enum, 2, "voca_system.INFO_LEVEL_OPTION"
      optional :saga, :enum, 3, "voca_system.SAGA_OPTION"
      optional :message, :string, 4
      optional :payload, :string, 5
    end
    add_enum "voca_system.INFO_LEVEL_OPTION" do
      value :INFO_LEVEL_OPTION_DEBUG, 0
      value :INFO_LEVEL_OPTION_INFO, 1
      value :INFO_LEVEL_OPTION_WARN, 2
      value :INFO_LEVEL_OPTION_ERROR, 3
    end
    add_enum "voca_system.SAGA_OPTION" do
      value :SAGA_OPTION_DECIDIM_ASSETS, 0
      value :SAGA_OPTION_DECIDIM_SEED, 1
      value :SAGA_OPTION_DECIDIM_ADMIN_CREATED, 2
      value :SAGA_OPTION_DECIDIM_READY, 3
    end
  end
end

module VocaSystem
  StrapiEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_system.StrapiEventRequest").msgclass
  INFO_LEVEL_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_system.INFO_LEVEL_OPTION").enummodule
  SAGA_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_system.SAGA_OPTION").enummodule
end
