# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Settings.proto", :syntax => :proto3) do
    add_message "VocaDecidim.Empty" do
    end
    add_message "VocaDecidim.GetSettingsResp" do
      optional :id, :uint64, 1
      optional :title, :string, 2
      optional :host, :string, 3
      optional :defaultLanguage, :string, 4
      optional :registerMode, :enum, 5, "VocaDecidim.REGISTER_OPTION"
    end
    add_message "VocaDecidim.SettingReq" do
      optional :title, :string, 1
      optional :host, :string, 2
      optional :defaultLanguage, :string, 3
      optional :registerMode, :enum, 4, "VocaDecidim.REGISTER_OPTION"
    end
    add_enum "VocaDecidim.REGISTER_OPTION" do
      value :REGISTER_AND_LOGIN, 0
      value :LOGIN, 1
      value :EXTERNAL, 2
    end
  end
end

module VocaDecidim
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaDecidim.Empty").msgclass
  GetSettingsResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaDecidim.GetSettingsResp").msgclass
  SettingReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaDecidim.SettingReq").msgclass
  REGISTER_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VocaDecidim.REGISTER_OPTION").enummodule
end
