# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Settings.proto for package 'VocaDecidim'

require 'grpc'
require 'Settings_pb'

module VocaDecidim
  module Settings
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'VocaDecidim.Settings'

      rpc :GetSettings, ::VocaDecidim::Empty, ::VocaDecidim::GetSettingsResp
      rpc :SetBasicSettings, ::VocaDecidim::SettingReq, ::VocaDecidim::GetSettingsResp
    end

    Stub = Service.rpc_stub_class
  end
end
