# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: decidim_healthcheck.proto for package 'voca_e2e'

require 'grpc'
require 'decidim_healthcheck_pb'

module VocaE2e
  module HealthcheckEvents
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'voca_e2e.HealthcheckEvents'

      rpc :DispatchEvent, ::VocaE2e::HealthcheckEventRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
