# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decidim_healthcheck.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("decidim_healthcheck.proto", :syntax => :proto3) do
    add_message "voca_e2e.HealthcheckEventRequest" do
      optional :instanceUUID, :string, 1
      optional :healthy, :bool, 2
      optional :saga, :enum, 3, "voca_e2e.SAGA_OPTION"
      optional :error, :enum, 4, "voca_e2e.ERROR_OPTION"
      optional :message, :string, 5
      optional :screenshot_url, :string, 6
    end
    add_enum "voca_e2e.SAGA_OPTION" do
      value :SAGA_OPTION_DECIDIM_HEALTHCHECK, 0
    end
    add_enum "voca_e2e.ERROR_OPTION" do
      value :ERROR_OPTION_DECIDIM_404, 0
      value :ERROR_OPTION_DECIDIM_HOMEPAGE, 1
      value :ERROR_OPTION_DECIDIM_CONDITIONS, 2
      value :ERROR_OPTION_DECIDIM_FAQ, 3
      value :ERROR_OPTION_DECIDIM_UNKNOWN, 4
    end
  end
end

module VocaE2e
  HealthcheckEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_e2e.HealthcheckEventRequest").msgclass
  SAGA_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_e2e.SAGA_OPTION").enummodule
  ERROR_OPTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("voca_e2e.ERROR_OPTION").enummodule
end
