// source: decidim.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.voca_decidim.DecidimOrganizationSMTPSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION');
goog.forwardDeclare('proto.voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.voca_decidim.DecidimOrganizationSMTPSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.voca_decidim.DecidimOrganizationSMTPSettings.displayName = 'proto.voca_decidim.DecidimOrganizationSMTPSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.voca_decidim.DecidimOrganizationSMTPSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voca_decidim.DecidimOrganizationSMTPSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromLabel: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fromEmail: jspb.Message.getFieldWithDefault(msg, 2, ""),
    address: jspb.Message.getFieldWithDefault(msg, 3, ""),
    port: jspb.Message.getFieldWithDefault(msg, 4, ""),
    authentication: jspb.Message.getFieldWithDefault(msg, 5, 0),
    username: jspb.Message.getFieldWithDefault(msg, 6, ""),
    password: jspb.Message.getFieldWithDefault(msg, 7, ""),
    domain: jspb.Message.getFieldWithDefault(msg, 8, ""),
    enableStarttlsAuto: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    opensslVerifyMode: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voca_decidim.DecidimOrganizationSMTPSettings;
  return proto.voca_decidim.DecidimOrganizationSMTPSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voca_decidim.DecidimOrganizationSMTPSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromLabel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPort(value);
      break;
    case 5:
      var value = /** @type {!proto.voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION} */ (reader.readEnum());
      msg.setAuthentication(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableStarttlsAuto(value);
      break;
    case 10:
      var value = /** @type {!proto.voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION} */ (reader.readEnum());
      msg.setOpensslVerifyMode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voca_decidim.DecidimOrganizationSMTPSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voca_decidim.DecidimOrganizationSMTPSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromLabel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFromEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPort();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAuthentication();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEnableStarttlsAuto();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getOpensslVerifyMode();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
};


/**
 * optional string from_label = 1;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getFromLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setFromLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string from_email = 2;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getFromEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setFromEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string address = 3;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string port = 4;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setPort = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional SETTINGS_SMTP_AUTHENTICATION_OPTION authentication = 5;
 * @return {!proto.voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getAuthentication = function() {
  return /** @type {!proto.voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.voca_decidim.SETTINGS_SMTP_AUTHENTICATION_OPTION} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setAuthentication = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string username = 6;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string password = 7;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string domain = 8;
 * @return {string}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional bool enable_starttls_auto = 9;
 * @return {boolean}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getEnableStarttlsAuto = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setEnableStarttlsAuto = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional SETTINGS_SMTP_OPENSSL_OPTION openssl_verify_mode = 10;
 * @return {!proto.voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION}
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.getOpensslVerifyMode = function() {
  return /** @type {!proto.voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.voca_decidim.SETTINGS_SMTP_OPENSSL_OPTION} value
 * @return {!proto.voca_decidim.DecidimOrganizationSMTPSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationSMTPSettings.prototype.setOpensslVerifyMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


