// source: decidim.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.voca_decidim.DecidimOrganizationFeatureFlagSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.repeatedFields_, null);
};
goog.inherits(proto.voca_decidim.DecidimOrganizationFeatureFlagSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.displayName = 'proto.voca_decidim.DecidimOrganizationFeatureFlagSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    availableAuthorizationsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    badgesEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    userGroupsEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    enableMachineTranslations: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    machineTranslationDisplayPriority: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voca_decidim.DecidimOrganizationFeatureFlagSettings;
  return proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAvailableAuthorizations(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBadgesEnabled(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUserGroupsEnabled(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableMachineTranslations(value);
      break;
    case 5:
      var value = /** @type {!proto.voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION} */ (reader.readEnum());
      msg.setMachineTranslationDisplayPriority(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAvailableAuthorizationsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getBadgesEnabled();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getUserGroupsEnabled();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getEnableMachineTranslations();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getMachineTranslationDisplayPriority();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * repeated string available_authorizations = 1;
 * @return {!Array<string>}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.getAvailableAuthorizationsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.setAvailableAuthorizationsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.addAvailableAuthorizations = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.clearAvailableAuthorizationsList = function() {
  return this.setAvailableAuthorizationsList([]);
};


/**
 * optional bool badges_enabled = 2;
 * @return {boolean}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.getBadgesEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.setBadgesEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool user_groups_enabled = 3;
 * @return {boolean}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.getUserGroupsEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.setUserGroupsEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool enable_machine_translations = 4;
 * @return {boolean}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.getEnableMachineTranslations = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.setEnableMachineTranslations = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION machine_translation_display_priority = 5;
 * @return {!proto.voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION}
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.getMachineTranslationDisplayPriority = function() {
  return /** @type {!proto.voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.voca_decidim.SETTINGS_MACHINE_TRANSLATION_PRIORITY_OPTION} value
 * @return {!proto.voca_decidim.DecidimOrganizationFeatureFlagSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFeatureFlagSettings.prototype.setMachineTranslationDisplayPriority = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


