// source: decidim.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.voca_decidim.DecidimOrganizationFileUploadSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.voca_decidim.DecidimOrganizationFileUploadSettings.repeatedFields_, null);
};
goog.inherits(proto.voca_decidim.DecidimOrganizationFileUploadSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.voca_decidim.DecidimOrganizationFileUploadSettings.displayName = 'proto.voca_decidim.DecidimOrganizationFileUploadSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.repeatedFields_ = [3,4,5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.voca_decidim.DecidimOrganizationFileUploadSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    maximumFileSizeAvatar: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    maximumFileSizeDefault: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    allowedContentTypesAdminList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    allowedContentTypesDefaultList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    allowedFileExtensionsAdminList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    allowedFileExtensionsDefaultList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voca_decidim.DecidimOrganizationFileUploadSettings;
  return proto.voca_decidim.DecidimOrganizationFileUploadSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaximumFileSizeAvatar(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaximumFileSizeDefault(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedContentTypesAdmin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedContentTypesDefault(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedFileExtensionsAdmin(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedFileExtensionsDefault(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voca_decidim.DecidimOrganizationFileUploadSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaximumFileSizeAvatar();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getMaximumFileSizeDefault();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getAllowedContentTypesAdminList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getAllowedContentTypesDefaultList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getAllowedFileExtensionsAdminList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getAllowedFileExtensionsDefaultList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * optional float maximum_file_size_avatar = 1;
 * @return {number}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getMaximumFileSizeAvatar = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setMaximumFileSizeAvatar = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float maximum_file_size_default = 2;
 * @return {number}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getMaximumFileSizeDefault = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setMaximumFileSizeDefault = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * repeated string allowed_content_types_admin = 3;
 * @return {!Array<string>}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getAllowedContentTypesAdminList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setAllowedContentTypesAdminList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.addAllowedContentTypesAdmin = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.clearAllowedContentTypesAdminList = function() {
  return this.setAllowedContentTypesAdminList([]);
};


/**
 * repeated string allowed_content_types_default = 4;
 * @return {!Array<string>}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getAllowedContentTypesDefaultList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setAllowedContentTypesDefaultList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.addAllowedContentTypesDefault = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.clearAllowedContentTypesDefaultList = function() {
  return this.setAllowedContentTypesDefaultList([]);
};


/**
 * repeated string allowed_file_extensions_admin = 5;
 * @return {!Array<string>}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getAllowedFileExtensionsAdminList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setAllowedFileExtensionsAdminList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.addAllowedFileExtensionsAdmin = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.clearAllowedFileExtensionsAdminList = function() {
  return this.setAllowedFileExtensionsAdminList([]);
};


/**
 * repeated string allowed_file_extensions_default = 6;
 * @return {!Array<string>}
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.getAllowedFileExtensionsDefaultList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.setAllowedFileExtensionsDefaultList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.addAllowedFileExtensionsDefault = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.voca_decidim.DecidimOrganizationFileUploadSettings} returns this
 */
proto.voca_decidim.DecidimOrganizationFileUploadSettings.prototype.clearAllowedFileExtensionsDefaultList = function() {
  return this.setAllowedFileExtensionsDefaultList([]);
};


